Controllers/StudentClassesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IdentitySample.Models;
using SchoolManagement.Model.Entity;
using SchoolManagement.Model.ViewModels;

namespace SchoolManagement.Controllers
{
    public class StudentClassesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private StudentClassVM studentClassVM = new StudentClassVM();

        // GET: StudentClasses
        public ActionResult Index()
        {
            var studentClasses = db.StudentClasses.Include(s => s.ClassName).Include(s => s.Section);
            return View(studentClasses.ToList());
        }

        // GET: StudentClasses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = db.StudentClasses.Find(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            return View(studentClass);
        }

        // GET: StudentClasses/Create
        public ActionResult Create()
        {
            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name");
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name");
            return View();
        }

        // POST: StudentClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ClassNameId,SectionId,Name")] StudentClass studentClass)
        {
            if (ModelState.IsValid)
            {
                studentClass.Name = studentClassVM.GetName();
                var std = new StudentClass() { Id=studentClass.Id,ClassNameId=studentClass.ClassNameId,SectionId=studentClass.SectionId,Name=studentClass.Name}; 
                db.StudentClasses.Add(std);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name", studentClass.ClassNameId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", studentClass.SectionId);
            return View(studentClass);
        }

        // GET: StudentClasses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = db.StudentClasses.Find(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name", studentClass.ClassNameId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", studentClass.SectionId);
            return View(studentClass);
        }

        // POST: StudentClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ClassNameId,SectionId")] StudentClass studentClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name", studentClass.ClassNameId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", studentClass.SectionId);
            return View(studentClass);
        }

        // GET: StudentClasses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentClass studentClass = db.StudentClasses.Find(id);
            if (studentClass == null)
            {
                return HttpNotFound();
            }
            return View(studentClass);
        }

        // POST: StudentClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentClass studentClass = db.StudentClasses.Find(id);
            db.StudentClasses.Remove(studentClass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/StudentClasses/Create.cshtml
@model SchoolManagement.Model.Entity.StudentClass
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>
        Add New Students Class
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "StudentClasses", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Student Class</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ClassNameId, "Class Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ClassNameId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SectionId, "Section", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SectionId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/StudentClasses/Delete.cshtml
@model SchoolManagement.Model.Entity.StudentClass

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Section.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Section.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shift.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shift.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/StudentClasses/Details.cshtml
@model SchoolManagement.Model.Entity.StudentClass

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Student Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Section.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Section.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shift.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shift.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassName.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/StudentClasses/Edit.cshtml
@model SchoolManagement.Model.Entity.StudentClass

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, "SectionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SectionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShiftId, "ShiftId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShiftId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShiftId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/StudentClasses/Index.cshtml
@model IEnumerable<SchoolManagement.Model.Entity.StudentClass>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Student Class list
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Create New", "Create")
        </small>
    </h1>
</div>

<div class="row">
<div class="col-xs-12">
    <table id="simple-table" class="table  table-bordered table-hover">
        <thead>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Section.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Shift.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClassName.Name)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Section.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shift.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassName.Name)
            </td>
            <td>
                <button class="btn btn-primary">
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                </button>
                @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                <button class="btn btn-danger">
                    <i class="fa fa-trash-o fa-lg"></i>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </button>
            </td>
        </tr>
            }

        </thead>
    </table>
</div>

</div>