Controllers/StudentApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SchoolManagement.Model.Entity;
using SchoolManagement.Model.ViewModels;
using PagedList;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Net.Mail;
using SchoolManagement.Models;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.Configuration;
using PayFast;
using PayFast.AspNet;
using IdentitySample.Models;
using System.Threading.Tasks;

namespace SchoolManagement.Controllers
{
    public class StudentApplicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private StudentApplicationVM stdApp = new StudentApplicationVM();
        // GET: StudentApplications
        public ActionResult Index2()
        {
            var studentapplications = db.Studentapplications.Include(s => s.ClassName);
            var username = User.Identity.GetUserName();
            return View(studentapplications.ToList().Where(x=>x.GuardianEmail == username));
        }
     
        public ActionResult Index(string option, string search,int? pageNumber, string sort)
        {
            var studentapplications = db.Studentapplications.Include(s => s.ClassName);

            //if a user choose the radio button option as Subject  
            if (option == "Surname")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(studentapplications.Where(x=>x.Surname.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 5));
            }
            else if (option == "Status")
            {
                return View(studentapplications.Where(x => x.Status.StartsWith(search)|| search == null).ToList().ToPagedList(pageNumber ?? 1, 5));
            }
            else
            {
                return View(studentapplications.Where(x => x.Name.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 3));
            }
        }
        public ActionResult ExportToExcel()
        {
            var gv = new GridView();
            gv.DataSource = db.Studentapplications.ToList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }
        // GET: StudentApplications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentApplication studentApplication = db.Studentapplications.Find(id);
            if (studentApplication == null)
            {
                return HttpNotFound();
            }
            return View(studentApplication);
        }
        public ActionResult ApproveApplication(int? id)
        {    
            StudentApplication studentApplication = db.Studentapplications.Find(id);
            if (studentApplication.Status == "Accepted" || studentApplication.Status == "Rejected")
            {
                TempData["AlertMessage"] = "The application has already been Rejected/Accepted";
                return RedirectToAction("Index");
            }
            else
            {
                studentApplication.Status = "Accepted";           
                db.Entry(studentApplication).State = EntityState.Modified;
              // db.Studentapplications.Add(studentApplication);
               db.SaveChanges();
                var mailTo = new List<MailAddress>();
                mailTo.Add(new MailAddress(studentApplication.GuardianEmail, studentApplication.GuardianName));
                var body = $"Hello {studentApplication.GuardianName}, Your child has been accepted to study at our school next year, please make sure you accept the offer within 7 days to avoid getting your offer forfeited. If you have accepted the offer, you will then be allowed to pay the deposit fee within 30 days to be unblocked for registration. <br/> Regards,<br/><br/> Nqabakazulu Comphrehesive High School <br/> .";

                SchoolManagement.Models.EmailService emailService = new SchoolManagement.Models.EmailService();
                emailService.SendEmail(new EmailContent()
                {
                    mailTo = mailTo,
                    mailCc = new List<MailAddress>(),
                    mailSubject = "Application Statement | Ref No.:" + studentApplication.Id,
                    mailBody = body,
                    mailFooter = "<br/> Many Thanks, <br/> <b>Nqabakazulu Comphrehesive High School</b>",
                    mailPriority = MailPriority.High,
                    mailAttachments = new List<Attachment>()

                });
                return RedirectToAction("Index");
            }

        }
        public ActionResult AcceptOffer(int? id)
        {
            StudentApplication studentApplication = db.Studentapplications.Find(id);

                studentApplication.Status = "Offer Accepted";
                db.Entry(studentApplication).State = EntityState.Modified;
                // db.Studentapplications.Add(studentApplication);
                db.SaveChanges();
                return RedirectToAction("Index2");

        }

        public ActionResult EmailstudentInfor(int? id)
        {
            Session["bookID"] = id;

            StudentApplication studentApplication = db.Studentapplications.Where(p => p.Id == id).FirstOrDefault();
            var username = User.Identity.GetUserName();
            var attachments = new List<Attachment>();
            attachments.Add(new Attachment(new MemoryStream(GeneratePDF(id)), "Proof of registration", "application/pdf"));
            var mailTo = new List<MailAddress>();
                mailTo.Add(new MailAddress(username, studentApplication.GuardianName));
                var body = $"Hello {studentApplication.GuardianName}, \n\n {studentApplication.Name} has been successfully registered at our school. Please Find the attached registration information(Proof of Registration)<br/> Regards,<br/><br/> Nqabakazulu Comphrehesive High School <br/> .";

                SchoolManagement.Models.EmailService emailService = new SchoolManagement.Models.EmailService();
            emailService.SendEmail(new EmailContent()
            {
                mailTo = mailTo,
                mailCc = new List<MailAddress>(),
                mailSubject = "Application Statement | Ref No.:" + studentApplication.Id,
                mailBody = body,
                mailFooter = "<br/> Many Thanks, <br/> <b>Nqabakazulu Comphrehesive High School</b>",
                mailPriority = MailPriority.High,
                mailAttachments = attachments

            });
            TempData["AlertMessage"] = $"{studentApplication.Name} has been successfully Registered";

            return RedirectToAction("Index2");
        }
        
        public ActionResult register(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentApplication studentApplication = db.Studentapplications.Find(id);
            if (studentApplication == null)
            {
                return HttpNotFound();
            }
            
            studentApplication.StudentNumber = stdApp.generateStudenbtNumber();
            studentApplication.Status = "Registered";
              db.Entry(studentApplication).State = EntityState.Modified;
                db.SaveChanges();

            var username = User.Identity.GetUserName();
            Student student = db.Students.Find(id);
            student.StudentNumber = stdApp.generateStudenbtNumber();
            student.Status = "Registered"; 
            db.Entry(student).State = EntityState.Modified;
            db.SaveChanges();
            return View(studentApplication);
            //return RedirectToAction("Index2");

        }
        public ActionResult RejectApplication(int? id)
        {
            StudentApplication studentApplication = db.Studentapplications.Find(id);
            if (studentApplication.Status == "Accepted" || studentApplication.Status == "Rejected")
            {
                TempData["AlertMessage"] = "The application has already been Rejected/Accepted";
                return RedirectToAction("Index");
            }
            else
            {
                studentApplication.Status = "Rejected";
                db.Entry(studentApplication).State = EntityState.Modified;
                db.SaveChanges();
                var mailTo = new List<MailAddress>();
                mailTo.Add(new MailAddress(studentApplication.GuardianEmail, studentApplication.GuardianName));
                var body = $"Hello {studentApplication.GuardianName}, Your child has been rejected to study at our school next year, this is due to not meeting the admissions criteria. <br/> Regards,<br/><br/> Nqabakazulu Comphrehesive High School</ <br/> .";

                SchoolManagement.Models.EmailService emailService = new SchoolManagement.Models.EmailService();
                emailService.SendEmail(new EmailContent()
                {
                    mailTo = mailTo,
                    mailCc = new List<MailAddress>(),

Controllers/SubjectController.cs
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using PagedList;
using IdentitySample.Models;
using SchoolManagement.Model.Entity;

namespace SchoolManagement.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class SubjectController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult SubjectView(int? id)
        {
            if (id == null)
            {
                var results = db.Subjects.ToList();
                return View(results);

            }
            else
            {
                var results = db.Subjects.Where(x => x.ClassNameId == id).ToList();
                return View(results);

            }
        }
        public ActionResult SubjectView2(int? id)
        {
            if (id == null)
            {
                var results = db.Subjects.ToList();
                return View(results);

            }
            else
            {
                var results = db.Subjects.Where(x => x.ClassNameId == id).ToList();
                return View(results);

            }
        }
        public ActionResult Index(string option, string search, int? pageNumber, string sort)
        {
            var Subject = db.Subjects.Include(c => c.ClassName);
           
               
            if (option == "ClassName")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(Subject.Where(x => x.ClassName.Name.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 8));
            }
            else if (option == "Code")
            {
                return View(Subject.Where(x => x.Code.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 5));
            }
            else
            {
                    return View(Subject.Where(x => x.Name.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 3));
               
                }
            }
        public ActionResult ExportToExcel()
        {
            var gv = new GridView();
            gv.DataSource = db.Studentapplications.ToList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }

        public ActionResult Create()
        {
            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id","Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Code,Theory,Mcq,Practical,Subject_Credit,ClassNameId")] Subject Subject)
        {

           
            if (ModelState.IsValid)
            {
                
                db.Subjects.Add(Subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name", Subject.ClassNameId); ;
            return View(Subject);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Subject Subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Subject);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject Subject = db.Subjects.Find(id);
            db.Subjects.Remove(Subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/StudentApplications/Delete.cshtml
@model SchoolManagement.Model.Entity.StudentApplication

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentApplication</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeLanguage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeLanguage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PresentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PresentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParmanentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParmanentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Religion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Religion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/StudentApplications/Index2.cshtml
@model IEnumerable<SchoolManagement.Model.Entity.StudentApplication>

<div class="page-header">
    <h1>
        Your Application details
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @*@Html.ActionLink("Create New", "Create")*@
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ClassName.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Surname)
                    </th>

                    @*<th>
                        @Html.DisplayNameFor(model => model.DOB)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.NID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Gender)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HomeLanguage)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Race)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PresentAddress)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ParmanentAddress)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.Religion)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StudentNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GuardianName)
                    </th>
                    <th>Action</th>
                </tr>

                @foreach (var item in Model)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassName.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>

                @*<td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.NID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomeLanguage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Race)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PresentAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParmanentAddress)
                </td>
                @*<td>
            @Html.DisplayFor(modelItem => item.Religion)
        </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>

                    <a href="@Url.Action("SubjectView", "Subject", new { id = item.ClassNameId })" rel="tooltip" title="Register" class="btn btn-primary btn-simple btn-xs">View Subjects<i class="fa fa-registered" aria-hidden="true"></i></a>

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GuardianName)
                </td>
                <td>
                    @if (item.Status == "Accepted")
                    {
                <a href="@Url.Action("AcceptOffer", "StudentApplications", new { id = item.Id })" onclick="return confirm('Are you sure you want to Accept this Offer, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Accept Offer" class="btn btn-success btn-simple btn-xs"><i class="fa fa-check" aria-hidden="true"></i></a>}

                    @if (item.Status == "Offer Accepted")
                    {
                <a href="@Url.Action("OnceOff", "StudentApplications", new { id = item.Id })" onclick="return confirm('Are you sure you want to Pay deposit fee, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Pay" class="btn btn-primary btn-simple btn-xs"><i style="font-size:24px" class="fa">&#xf1ed;</i></a>}

                    @if (item.Status == "Deposit Paid")
                    {
                <a href="@Url.Action("register", "StudentApplications", new { id = item.Id })" onclick="return confirm('Are you sure you want to register, click Ok to Confirm, Or Cancel');" rel="tooltip" title="Register" class="btn btn-success btn-simple btn-xs"><i class="fa fa-registered" aria-hidden="true"></i></a>}
                </td>
            </tr>
                    }

                </thead>
        </table>
    </div>
</div>

Views/StudentApplications/register.cshtml
@model SchoolManagement.Model.Entity.StudentApplication

@{ ViewBag.Title = "Resister Details"; }

@*<h2 class="title text-center">@ViewBag.Title</h2>*@
<div class="row">
    <div class="col-md-4">
        <h3>Student Registration Details</h3>
        <table class="table">

            <tr>
                <th>Class Id</th>
                <td>
                    <div class="input-group">
                        @Html.DisplayFor(m => m.ClassName.Id, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.ClassName.Id, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>Class name  </th>
                <td>
                    <div class="input-group">
                        @Html.DisplayFor(m => m.ClassName.Name, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.ClassName.Name, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.DOB)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.DOB, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.DOB, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.Name)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Name, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.NID)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.NID, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.NID, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.ParmanentAddress)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.ParmanentAddress, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.ParmanentAddress, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.PresentAddress)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.PresentAddress, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.PresentAddress, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-4">
        @*<h3>Booking details</h3>*@
        <table class="table">
            <tr>
                <th>@Html.LabelFor(model => model.Email)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Registration Number" } })
                    </div>
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </td>
            </tr>
           
            <tr>
                <th>@Html.LabelFor(model => model.Gender)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Gender, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Gender, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.HomeLanguage)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.HomeLanguage, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.HomeLanguage, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.Race)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Race, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Race, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.Religion)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Religion, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Religion, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.Surname)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.Surname, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.Surname, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.StudentNumber)</th>
                <td>
                    <div class="input-group">

                        @Html.DisplayFor(m => m.StudentNumber, new { @class = "form-control", @placeholder = "Registration Number" })
                    </div>
                    @Html.ValidationMessageFor(m => m.StudentNumber, "", new { @class = "text-danger" })
                </td>
            </tr>
            @*<tr>
                <th>@Html.LabelFor(model => model.subject)</th>
                <td>
                    <a href="@Url.Action("SubjectView2", "Subject", new { id = Model.ClassNameId })" rel="tooltip" title="Register" class="btn btn-primary btn-simple btn-xs">View Subjects<i class="fa fa-registered" aria-hidden="true"></i></a>

                </td>
            </tr>*@
        </table>
    </div>
</div>



<div class="row text-center">
    @Html.ActionLink("Register", "EmailstudentInfor", "StudentApplications", new { id = Model.Id }, new { @class = "btn btn-success" })
</div>