Models/Entity/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolManagement.Model.Entity
{
    public class Subject
    {
        [Key]
        public int Id { get; set; }

        [Required,DisplayName("Subject Name")]
        public string Name { get; set; }

        [Required, DisplayName("Subject Code")]
        public string Code { get; set; }
        public double Subject_Credit { get; set; }

        public string SubjectAssignTo { get; set; }
        public int Theory { get; set; }
        public int Mcq { get; set; }
        public int Practical { get; set; }
        public int ClassNameId { get; set; }
        public virtual ClassName ClassName { get; set; }
        
    }
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PayFast;
using PayFast.AspNet;
using SchoolManagement.Model.Entity;
using SchoolManagement.Models;
using IdentitySample.Models;

namespace SchoolManagement.Controllers
{
    public class StudentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Students
        public ActionResult Index()
        {
            var username = User.Identity.GetUserName();

            return View(db.Students.ToList().Where(x => x.UserName == username));
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Surname,DateOfBirth,Gender,Email,PresentAddress,deposit,Tuition,BalanceDue,UserName,NID,subject,StudentNumber,GuardianName,Status")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,DateOfBirth,Gender,Email,PresentAddress,deposit,Tuition,BalanceDue,UserName,NID,subject,StudentNumber,GuardianName,Status")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public StudentsController()
        {
            this.payFastSettings = new PayFastSettings();
            this.payFastSettings.MerchantId = ConfigurationManager.AppSettings["MerchantId"];
            this.payFastSettings.MerchantKey = ConfigurationManager.AppSettings["MerchantKey"];
            this.payFastSettings.PassPhrase = ConfigurationManager.AppSettings["PassPhrase"];
            this.payFastSettings.ProcessUrl = ConfigurationManager.AppSettings["ProcessUrl"];
            this.payFastSettings.ValidateUrl = ConfigurationManager.AppSettings["ValidateUrl"];
            this.payFastSettings.ReturnUrl = ConfigurationManager.AppSettings["ReturnUrl"];
            this.payFastSettings.CancelUrl = ConfigurationManager.AppSettings["CancelUrl"];
            this.payFastSettings.NotifyUrl = ConfigurationManager.AppSettings["NotifyUrl"];
        }
        //Payment
        #region Fields

        private readonly PayFastSettings payFastSettings;

        #endregion Fields

        #region Constructor

        //public ApprovedOwnersController()
        //{

        //}

        #endregion Constructor

        #region Methods



        public ActionResult Recurring()
        {
            var recurringRequest = new PayFastRequest(this.payFastSettings.PassPhrase);

            // Merchant Details
            recurringRequest.merchant_id = this.payFastSettings.MerchantId;
            recurringRequest.merchant_key = this.payFastSettings.MerchantKey;
            recurringRequest.return_url = this.payFastSettings.ReturnUrl;
            recurringRequest.cancel_url = this.payFastSettings.CancelUrl;
            recurringRequest.notify_url = this.payFastSettings.NotifyUrl;

            // Buyer Details
            recurringRequest.email_address = "sbtu01@payfast.co.za";

            // Transaction Details
            recurringRequest.m_payment_id = "8d00bf49-e979-4004-228c-08d452b86380";
            recurringRequest.amount = 20;
            recurringRequest.item_name = "Recurring Option";
            recurringRequest.item_description = "Some details about the recurring option";

            // Transaction Options
            recurringRequest.email_confirmation = true;
            recurringRequest.confirmation_address = "drnendwandwe@gmail.com";

            // Recurring Billing Details
            recurringRequest.subscription_type = SubscriptionType.Subscription;
            recurringRequest.billing_date = DateTime.Now;
            recurringRequest.recurring_amount = 20;
            recurringRequest.frequency = BillingFrequency.Monthly;
            recurringRequest.cycles = 0;

            var redirectUrl = $"{this.payFastSettings.ProcessUrl}{recurringRequest.ToString()}";

            return Redirect(redirectUrl);
        }
        //public ActionResult pay(int? id)
        //{
        //    StudentApplication studentApplication = db.Studentapplications.Find(id);
        //    var priceId = db.ClassFees.Where(p => p.ClassNameId == studentApplication.ClassNameId).Select(p => p.FeeTypeId).FirstOrDefault();
        //    var price = db.FeeTypes.Where(p => p.Id == priceId).Select(p => p.FeeAmount).FirstOrDefault();
        //    studentApplication.Status = "Paid";
        //    db.Entry(studentApplication).State = EntityState.Modified;

        //    // db.Studentapplications.Add(studentApplication);
        //    db.SaveChanges();
        //    return RedirectToAction("Index2");

        //}
        public ActionResult OnceOff(int? id)
        {
            var onceOffRequest = new PayFastRequest(this.payFastSettings.PassPhrase);

            // Merchant Details
            onceOffRequest.merchant_id = this.payFastSettings.MerchantId;
            onceOffRequest.merchant_key = this.payFastSettings.MerchantKey;
            onceOffRequest.return_url = this.payFastSettings.ReturnUrl;
            onceOffRequest.cancel_url = this.payFastSettings.CancelUrl;
            onceOffRequest.notify_url = this.payFastSettings.NotifyUrl;

            // Buyer Details

            onceOffRequest.email_address = "sbtu01@payfast.co.za";
            //onceOffRequest.email_address = "sbtu01@payfast.co.za";
            // Transaction Details

            StudentApplication studentApplication = db.Studentapplications.Find(id);
            //var price = db.FeeTypes.Where(p => p.Id == priceId.FeeTypeId && p.Name == "Deposit").FirstOrDefault();
            studentApplication.Status = "Tuition Paid";

            db.Entry(studentApplication).State = EntityState.Modified;
            db.SaveChanges();
            Student student = db.Students.Find(id);
            //student.deposit = SchoolLogic.getPrice("Deposit", (priceId.FeeTypeId + 1));
            //student.deposit = price.FeeAmount;
            

            var mailTo = new List<MailAddress>();
            mailTo.Add(new MailAddress(studentApplication.GuardianEmail, studentApplication.GuardianName));
            var body = $"Hello {studentApplication.GuardianName}, Amount Paid {student.Tuition}, Amount Remaining {student.BalanceDue}, Student Number {studentApplication.StudentNumber}, First Name {studentApplication.Name}, Student Surname {studentApplication.Surname}, Date:{System.DateTime.Now.Date}<br/> Regards,<br/><br/> Bright Ideas <br/> .";

            SchoolManagement.Models.EmailService emailService = new SchoolManagement.Models.EmailService();
            emailService.SendEmail(new EmailContent()
            {
                mailTo = mailTo,
                mailCc = new List<MailAddress>(),
                mailSubject = "Application Statement | Ref No.:" + studentApplication.Id,
                mailBody = body,
                mailFooter = "<br/> Many Thanks, <br/> <b>Bright Ideas</b>",
                mailPriority = MailPriority.High,

Controllers/SubjectController.cs
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using PagedList;
using IdentitySample.Models;
using SchoolManagement.Model.Entity;

namespace SchoolManagement.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class SubjectController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult SubjectView(int? id)
        {
            if (id == null)
            {
                var results = db.Subjects.ToList();
                return View(results);

            }
            else
            {
                var results = db.Subjects.Where(x => x.ClassNameId == id).ToList();
                return View(results);

            }
        }
        public ActionResult SubjectView2(int? id)
        {
            if (id == null)
            {
                var results = db.Subjects.ToList();
                return View(results);

            }
            else
            {
                var results = db.Subjects.Where(x => x.ClassNameId == id).ToList();
                return View(results);

            }
        }
        public ActionResult Index(string option, string search, int? pageNumber, string sort)
        {
            var Subject = db.Subjects.Include(c => c.ClassName);
           
               
            if (option == "ClassName")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(Subject.Where(x => x.ClassName.Name.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 8));
            }
            else if (option == "Code")
            {
                return View(Subject.Where(x => x.Code.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 5));
            }
            else
            {
                    return View(Subject.Where(x => x.Name.StartsWith(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 3));
               
                }
            }
        public ActionResult ExportToExcel()
        {
            var gv = new GridView();
            gv.DataSource = db.Studentapplications.ToList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }

        public ActionResult Create()
        {
            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id","Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Code,Theory,Mcq,Practical,Subject_Credit,ClassNameId")] Subject Subject)
        {

           
            if (ModelState.IsValid)
            {
                
                db.Subjects.Add(Subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClassNameId = new SelectList(db.ClassNames, "Id", "Name", Subject.ClassNameId); ;
            return View(Subject);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Subject Subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Subject);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject Subject = db.Subjects.Find(id);
            if (Subject == null)
            {
                return HttpNotFound();
            }
            return View(Subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject Subject = db.Subjects.Find(id);
            db.Subjects.Remove(Subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Subject/Create.cshtml
@model SchoolManagement.Model.Entity.Subject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Add New Subject
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @*<input type="submit" class="btn btn-success" value="Save" />*@
            @Html.ActionLink("Back to List", "Index", "Subject", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>Subject</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Subject_Credit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject_Credit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject_Credit, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Mcq, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mcq, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mcq, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Practical, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Practical, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Practical, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClassNameId, "Class Name ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ClassNameId", null, "--Select--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ClassNameId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Subject" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Subject/Delete.cshtml
@model SchoolManagement.Model.Entity.Subject

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentClass)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Subject_Credit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subject_Credit)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.SubjectAssignTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubjectAssignTo)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Theory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Theory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mcq)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mcq)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Practical)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Practical)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Subject/Edit.cshtml
@model SchoolManagement.Model.Entity.Subject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h1>
        Edit Subjects
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index", "Students", null, new { @class = "btn btn-info" })
        </small>
    </h1>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Course</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Subject_Credit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject_Credit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject_Credit, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SubjectAssignTo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SubjectAssignTo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SubjectAssignTo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Mcq, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mcq, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mcq, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Practical, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Practical, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Practical, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ClassNameId, "Class Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ClassNameId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ClassNameId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Subject/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SchoolManagement.Model.Entity.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>
        Subject list
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Create New", "Create")
        </small>
    </h1>
</div>

@using (Html.BeginForm("Index", "Subject", FormMethod.Get))
{
    //the following are search options

    <b> Search Option: </b>@*@Html.RadioButton("option", "StudentClass") <text>StudentClass</text>*@ @Html.RadioButton("option", "Name") <text>Name </text>
    @Html.RadioButton("option", "Code")<text>Subject Code</text> @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}

@if (Model.Count() == 0)
{
    <tr>
        <td colspan="3"> Records not found </td>
    </tr>
}
else
{
    <div class="row">
        <div class="col-xs-12">
            <table id="simple-table" class="table  table-bordered table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.First().ClassName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Code)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Subject_Credit)
                        </th>
                        @*<th>
                                @Html.DisplayNameFor(model => model.SubjectAssignTo)
                            </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.First().Theory)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Mcq)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Practical)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Total)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ClassName.Name)                             
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Subject_Credit)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Subject_Credit)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Theory)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mcq)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Practical)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>

                            <td>
                                <button class="btn btn-primary">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                </button>
                                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                            <button class="btn btn-danger">
                                <i class="fa fa-trash-o fa-lg"></i>
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                </button>
</td>
                        </tr>
                    }

                </thead>
            </table>
        </div>
    </div>

}
@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
{
    pageNumber,
    option = Request.QueryString["option"],
    search = Request.QueryString["search"]
}))